apiVersion: v1
kind: Service
metadata:
  name: sampleapp-service
  namespace: sampleapp
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    frontedBy: sampleapp
  type: LoadBalancer
